/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zeta.projetozeta.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Wagner N. Junior
 */
public class Descricao extends javax.swing.JPanel {

    /**
     * Creates new form Descricao
     */
    public Descricao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIcone = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelIDA = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        nomeOrigem = new javax.swing.JLabel();
        nomeDestino = new javax.swing.JLabel();
        labelOrigem = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        panelMonitorar = new javax.swing.JPanel();
        bMonitorar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        labelIcone.setText("Azul");

        labelIDA.setText("IDA");

        labelData.setText("Sab 30 Dez 2017");

        nomeOrigem.setText("São Paulo");

        nomeDestino.setText("Belém");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(labelIDA)))
                .addGap(58, 58, 58)
                .addComponent(nomeOrigem)
                .addGap(58, 58, 58)
                .addComponent(nomeDestino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelIDA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelData)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeOrigem)
                    .addComponent(nomeDestino))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        labelOrigem.setText("19:30");

        labelDestino.setText("00:00");

        panelMonitorar.setBackground(new java.awt.Color(0, 232, 73));

        bMonitorar.setBackground(new java.awt.Color(255, 255, 255));
        bMonitorar.setText("Monitorar");
        bMonitorar.setBorder(null);
        bMonitorar.setBorderPainted(false);
        bMonitorar.setContentAreaFilled(false);
        bMonitorar.setFocusable(false);
        bMonitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMonitorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMonitorarLayout = new javax.swing.GroupLayout(panelMonitorar);
        panelMonitorar.setLayout(panelMonitorarLayout);
        panelMonitorarLayout.setHorizontalGroup(
            panelMonitorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMonitorarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bMonitorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        panelMonitorarLayout.setVerticalGroup(
            panelMonitorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMonitorarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bMonitorar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIcone)
                .addGap(99, 99, 99)
                .addComponent(labelOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(labelDestino)
                .addGap(36, 36, 36)
                .addComponent(panelMonitorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelOrigem)
                        .addComponent(labelDestino)
                        .addComponent(labelIcone))
                    .addComponent(panelMonitorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bMonitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMonitorarActionPerformed
        

    }//GEN-LAST:event_bMonitorarActionPerformed

    public JButton getbMonitorar() {
        return bMonitorar;
    }

    public void setbMonitorar(JButton bMonitorar) {
        this.bMonitorar = bMonitorar;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLabelData() {
        return labelData;
    }

    public void setLabelData(JLabel labelData) {
        this.labelData = labelData;
    }

    public JLabel getLabelDestino() {
        return labelDestino;
    }

    public void setLabelDestino(JLabel labelDestino) {
        this.labelDestino = labelDestino;
    }

    public JLabel getLabelIDA() {
        return labelIDA;
    }

    public void setLabelIDA(JLabel labelIDA) {
        this.labelIDA = labelIDA;
    }

    public JLabel getLabelIcone() {
        return labelIcone;
    }

    public void setLabelIcone(JLabel labelIcone) {
        this.labelIcone = labelIcone;
    }

    public JLabel getLabelOrigem() {
        return labelOrigem;
    }

    public void setLabelOrigem(JLabel labelOrigem) {
        this.labelOrigem = labelOrigem;
    }

    public JLabel getNomeDestino() {
        return nomeDestino;
    }

    public void setNomeDestino(JLabel nomeDestino) {
        this.nomeDestino = nomeDestino;
    }

    public JLabel getNomeOrigem() {
        return nomeOrigem;
    }

    public void setNomeOrigem(JLabel nomeOrigem) {
        this.nomeOrigem = nomeOrigem;
    }

    public JPanel getPanelMonitorar() {
        return panelMonitorar;
    }

    public void setPanelMonitorar(JPanel panelMonitorar) {
        this.panelMonitorar = panelMonitorar;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMonitorar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelIDA;
    private javax.swing.JLabel labelIcone;
    private javax.swing.JLabel labelOrigem;
    private javax.swing.JLabel nomeDestino;
    private javax.swing.JLabel nomeOrigem;
    private javax.swing.JPanel panelMonitorar;
    // End of variables declaration//GEN-END:variables
}
